<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <AssemblyName>Link.Windows.Installer</AssemblyName>
    <RootNamespace>Link.Windows.Installer</RootNamespace>
    <Version>0.7.0</Version>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\Link.Windows.Installer.Core\Link.Windows.Installer.Core.csproj" />
  </ItemGroup>
</Project>
